version: "3"
services:
    php-fpm:
        build: install/php-fpm
        ports:
            - 9010:9000
        volumes:
            - ./code:/var/www/html/
        links:
            - db
    nginx:
        build: install/nginx
        ports:
            - 8080:80
        volumes:
            - ./code:/var/www/html/        
        links:
            - php-fpm
    db:
        image: mysql:5.6
        ports:
            - 3308:3306
        restart: always
        environment:
            MYSQL_DATABASE: MyDB
            MYSQL_USER: MyDB
            MYSQL_PASSWORD: mydbpassword
            MYSQL_ROOT_PASSWORD: rootpassword
        volumes:
            - MysqlVolume:/var/lib/mysql
    code-server:
        image: lscr.io/linuxserver/code-server:4.89.0
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Jakarta
            - PASSWORD=password #optional
            - HASHED_PASSWORD= #optional
            - SUDO_PASSWORD=password #optional
            - SUDO_PASSWORD_HASH= #optional
            - PROXY_DOMAIN=code-server.my.domain #optional
            - DEFAULT_WORKSPACE=/config/workspace #optional
        volumes:
            - ./code:/config/workspace
        ports:
            - 8308:8443
        restart: unless-stopped

volumes:
  MysqlVolume:
